-- crea_schemas.sql
CREATE SCHEMA IF NOT EXISTS co;
CREATE SCHEMA IF NOT EXISTS mx;
CREATE SCHEMA IF NOT EXISTS ec;
CREATE SCHEMA IF NOT EXISTS pe;

-- privilegios mínimos para el usuario de app
GRANT USAGE ON SCHEMA co, mx, ec, pe TO appuser;
GRANT ALL ON ALL TABLES IN SCHEMA co, mx, ec, pe TO appuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA co GRANT ALL ON TABLES TO appuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA mx GRANT ALL ON TABLES TO appuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA ec GRANT ALL ON TABLES TO appuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA pe GRANT ALL ON TABLES TO appuser;
